### ISSUE TITLE
Implement comprehensive observability stack

### ISSUE THREAD

**Issue by bvansomeren** [CoffeeSprout/moxxie#23]
## Description
Implement comprehensive observability stack for distributed Moxxie instances.

## Problem
Current plan lacks proper observability for a distributed system, making troubleshooting and performance optimization difficult.

## Tasks
- [ ] Implement distributed tracing with OpenTelemetry
- [ ] Add structured logging with correlation IDs
- [ ] Create custom metrics for business KPIs
- [ ] Set up trace context propagation
- [ ] Implement SLI/SLO tracking
- [ ] Add performance profiling endpoints
- [ ] Create observability dashboards

### Distributed Tracing
```java
@ApplicationScoped
public class TracingConfig {
    @Produces
    @Singleton
    public Tracer tracer() {
        return OpenTelemetry.builder()
            .addSpanProcessor(JaegerSpanProcessor.create())
            .build()
            .getTracer("moxxie");
    }
}

@Interceptor
public class TracingInterceptor {
    @AroundInvoke
    public Object trace(InvocationContext context) {
        var span = tracer.spanBuilder(context.getMethod().getName())
            .setAttribute("instance.id", instanceId)
            .setAttribute("location", location)
            .startSpan();
        
        try (var scope = span.makeCurrent()) {
            return context.proceed();
        } finally {
            span.end();
        }
    }
}
```

### Structured Logging
```java
@RequestScoped
public class CorrelationContext {
    private String correlationId = UUID.randomUUID().toString();
    private String traceId;
    private String spanId;
    
    public Map<String, String> getMDC() {
        return Map.of(
            "correlation_id", correlationId,
            "trace_id", traceId,
            "span_id", spanId,
            "instance_id", instanceId,
            "location", location
        );
    }
}
```

### Business Metrics
```java
@ApplicationScoped
public class BusinessMetrics {
    // VM lifecycle metrics
    Counter vmCreated;
    Counter vmDeleted;
    Histogram vmCreationDuration;
    
    // Resource utilization
    Gauge cpuUtilization;
    Gauge memoryUtilization;
    Gauge storageUtilization;
    
    // API performance
    Timer apiLatency;
    Counter apiErrors;
    
    // Business KPIs
    Gauge costPerHour;
    Counter migrationSuccess;
    Counter migrationFailure;
}
```

### SLI/SLO Definitions
```yaml
SLIs:
  - name: api_availability
    query: sum(rate(http_requests_total[5m])) - sum(rate(http_requests_failed[5m])) / sum(rate(http_requests_total[5m]))
  
  - name: api_latency_p99
    query: histogram_quantile(0.99, http_request_duration_seconds_bucket)
  
  - name: vm_creation_success_rate
    query: rate(vm_creation_success[5m]) / rate(vm_creation_total[5m])

SLOs:
  - sli: api_availability
    target: 99.9
    window: 30d
  
  - sli: api_latency_p99
    target: 500ms
    window: 7d
  
  - sli: vm_creation_success_rate
    target: 99.5
    window: 30d
```

### Observability Stack
```yaml
components:
  traces:
    - Jaeger or Tempo
    - OpenTelemetry collector
  
  metrics:
    - Prometheus
    - Grafana
    - AlertManager
  
  logs:
    - Loki or Elasticsearch
    - Fluentd/Fluent Bit
    - Kibana or Grafana
  
  dashboards:
    - RED metrics (Rate, Errors, Duration)
    - USE metrics (Utilization, Saturation, Errors)
    - Business KPIs
    - SLO tracking
```

## Success Criteria
- [ ] Full request tracing across all components
- [ ] Correlation IDs link logs, traces, and metrics
- [ ] P99 latency visible in real-time
- [ ] SLO breach alerts configured
- [ ] Root cause analysis possible via traces
- [ ] Performance bottlenecks identifiable
- [ ] Business metrics drive decisions
